import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import axe from 'axe-core';

const baseURL = process.env.QUIET_LOOP_URL || 'http://127.0.0.1:5173';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
const page = await context.newPage();
const errors = [];
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
page.on('pageerror', (error) => errors.push(error.message));
await page.goto(baseURL, { waitUntil: 'networkidle' });
await assert.equal(await page.locator('html').getAttribute('lang'), 'en');
await assert.ok(await page.locator('main h1').count() === 1, 'one main h1 is present');
await page.evaluate(axe.source);
const axeResult = await page.evaluate(async () => window.axe.run());
const serious = axeResult.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact));
assert.deepEqual(serious, [], `serious axe violations: ${serious.map((violation) => violation.id).join(', ')}`);
await page.getByRole('button', { name: 'Add your first card' }).click();
await page.locator('textarea[name="front"]').first().fill('How do I say thank you?');
await page.locator('textarea[name="back"]').first().fill('Gracias');
await page.getByRole('button', { name: 'Add to your loop' }).click();
await page.getByRole('button', { name: 'Today' }).click();
await page.getByRole('button', { name: 'Choose today’s small set' }).click();
await page.getByRole('button', { name: 'Show answer' }).click();
await assert.ok(await page.getByText('Gracias').isVisible());
await page.getByRole('button', { name: 'Archive this card' }).click();
await page.locator('#archive-reason').selectOption('Already familiar');
await page.getByRole('button', { name: 'Archive card' }).click();
await page.getByRole('heading', { name: 'Your next ten minutes can be quiet.' }).waitFor();
await page.reload({ waitUntil: 'networkidle' });
await assert.ok(await page.getByText('Make a few language cards').isVisible());
assert.deepEqual(errors, [], `console errors before offline test: ${errors.join(' | ')}`);
await context.setOffline(true);
await page.reload({ waitUntil: 'domcontentloaded' });
await assert.ok(await page.locator('main').count() === 1, 'cached app shell works offline');
await browser.close();
console.log('Browser smoke and offline cache passed.');
